/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.model.Employee;
import cn.services.LoginServices;
import cn.services.LoginServicesFactory;
import cn.web.form.LoginForm;

public class LoginAction extends Action 
{
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println();
		System.out.println("-----LoginAction----");
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		String name = loginForm.getName();
		String password =loginForm.getPassword();
		
		Employee user = new Employee();
		user.setUser_name(name);
		user.setPassword(password);
		
		
		LoginServices logSer = LoginServicesFactory.getServices();
		
		String path = logSer.checkUser(user);
		
		List departmentSingleList = logSer.getDepartment_single(user);
		System.out.println("----departmentSingleList----"+departmentSingleList);
		request.setAttribute("departmentSingleList", departmentSingleList);
		
		ActionForward forward = mapping.findForward(path);
		return forward;
	}
}